In [3]:
import numpy as np
a=np.arange(1,11)
print(a)
print(a[2:7])
print(a[1:8:2])
print(a[-3])

[ 1  2  3  4  5  6  7  8  9 10]
[3 4 5 6 7]
[2 4 6 8]
8


In [4]:
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(arr_2d[2,0])
print(arr_2d[2])
print(arr_2d[:,2])

7
[7 8 9]
[3 6 9]


In [8]:
ad=np.array([1,4,7,2,6,9,0])
print(np.sort(ad))
bd=np.array([[2,4,2],[1,5,3],[9,5,4]])
print(np.sort(bd,axis=0))
print(np.sort(bd,axis=1))

[0 1 2 4 6 7 9]
[[1 4 2]
 [2 5 3]
 [9 5 4]]
[[2 2 4]
 [1 3 5]
 [4 5 9]]


In [16]:
f=np.array([2,345,54,24,235,76,545,5])
print(f[f%5==0])
mask= f>100
print(f[mask])
o=np.where(f>80)
print(f[o])
gd=np.where(f>80,f*2,f)
print(gd)

[345 235 545   5]
[345 235 545]
[345 235 545]
[   2  690   54   24  470   76 1090    5]


In [18]:
ar_1=np.array([1,2,3])
ar_2=np.array([4,5,6])
d=np.concatenate((ar_1,ar_2));
print(d)

[1 2 3 4 5 6]


In [27]:
fe=np.arange(1,13)
fr=np.array([2,3,4])
print(fe.shape==fr.shape)
tr1=np.array([[1,20],[3,4]])
tr2=np.array([2,5])
tr3=np.array([4,5])
tr_t=np.vstack((tr1,tr2))
tr_p=np.hstack((tr2,tr3))
delr=np.delete(tr3,0)
print(delr)
print(tr_t)
print(tr_p)

False
[5]
[[ 1 20]
 [ 3  4]
 [ 2  5]]
[2 5 4 5]
