## numpy learn

In [2]:
import numpy as np

a = np.array([1, 2, 3,4])
b=np.array([[133,23,32,23],[23,3,42,1]])
print(a, "\n ",b,"\n",a+b,"\n",a*b)

[1 2 3 4] 
  [[133  23  32  23]
 [ 23   3  42   1]] 
 [[134  25  35  27]
 [ 24   5  45   5]] 
 [[133  46  96  92]
 [ 23   6 126   4]]


In [3]:
aj=np.ones((3,2))
bj=np.zeros((1,5))
cj=np.full((2,3),4)
rand= np.random.random((2,3))
range= np.arange(2,4)
identity=np.eye(4)
print(aj)
print(bj)
print(cj)
print(rand)
print(range)
print(identity)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0. 0. 0. 0.]]
[[4 4 4]
 [4 4 4]]
[[0.25895557 0.649346   0.47252913]
 [0.4006856  0.20690303 0.39023345]]
[2 3]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
a=np.array([[2,3,4],
           [3,5,4]])
print("shape",a.shape)
print("dimension",a.ndim)
print("size",a.size)
print("dtype",a.dtype)

shape (2, 3)
dimension 2
size 6
dtype int64


In [6]:
a=np.arange(0,12)
reshape=a.reshape(3,4)
flatten=reshape.flatten()
ravel=reshape.ravel()
transpose=reshape.T
print(reshape)
# print(flatten)
print(ravel)
# print(transpose)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
